# scene: engine\test\viviModel\scene #engine\modelPreview\scene #gameplayScene
# scene: engine\test\pbrScene\scene #engine\modelPreview\scene #gameplayScene
scene: gameplayScene
maximumDeltaTime: 0.05
fixedDeltaTime: 0.016666666666
fullscreen: false
debugSceneLoading: false
godMode: true
soundEnabled: false
showFps: true
libraries:
  - Game.dll