scene: engine\test\viviModel\scene #engine\modelPreview\scene #gameplayScene
maximumDeltaTime: 0.05
fixedDeltaTime: 0.016666666666
fullscreen: false
debugSceneLoading: false
vsync: false
godMode: true
soundEnabled: false
showFps: true
libraries:
  - Game.dll
  - Test.dll