scene: gameplayScene #engine\modelPreview\scene #gameplayScene
maximumDeltaTime: 0.05
fixedDeltaTime: 0.016666666666
fullscreen: false
debugSceneLoading: false
vsync: false
godMode: false
soundEnabled: false
libraries:
  - Game.dll